export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_CURRENT_ATTEMPT = 'UPDATE_CURRENT_ATTEMPT';
export const GENERATE_WORD_SET = 'GENERATE_WORD_SET';
export const UPDATE_WORD_SET = 'UPDATE_WORD_SET';
export const UPDATE_DISABLED_LETTERS = 'UPDATE_DISABLED_LETTERS';
export const UPDATE_GAME_OVER = 'UPDATE_GAME_OVER';
export const UPDATE_CORRECT_WORD = 'UPDATE_CORRECT_WORD';